# Form implementation generated from reading ui file '/home/ilya/Projects/OpenCRM/modules/ui_files/VirtualSklad.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Window(object):
    def setupUi(self, Window):
        Window.setObjectName("Window")
        Window.resize(700, 480)
        Window.setMinimumSize(QtCore.QSize(700, 480))
        self.centralwidget = QtWidgets.QWidget(parent=Window)
        self.centralwidget.setObjectName("centralwidget")
        Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Window)
        self.statusbar.setObjectName("statusbar")
        Window.setStatusBar(self.statusbar)
        self.actionfsdhjsgkl_dfjg = QtGui.QAction(parent=Window)
        self.actionfsdhjsgkl_dfjg.setCheckable(True)
        self.actionfsdhjsgkl_dfjg.setChecked(False)
        self.actionfsdhjsgkl_dfjg.setObjectName("actionfsdhjsgkl_dfjg")
        self.menu.addAction(self.actionfsdhjsgkl_dfjg)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(Window)
        QtCore.QMetaObject.connectSlotsByName(Window)

    def retranslateUi(self, Window):
        _translate = QtCore.QCoreApplication.translate
        Window.setWindowTitle(_translate("Window", "MainWindow"))
        self.menu.setTitle(_translate("Window", "Файл"))
        self.actionfsdhjsgkl_dfjg.setText(_translate("Window", "fsdhjsgkl;dfjg"))
